trigger:
  branches:
    include: ['master']
  tags:
    include: ['v*']
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - "*.md"
    - "docs/*"
    - "LICENSE-*"
schedules:
- cron: "3 3 3 * *"
  displayName: Monthly Build
  branches:
    include:
    - master
variables:
  windows_vm: windows-latest
  mac_vm: macOS-latest
  linux_vm: ubuntu-latest

stages:
- stage: style
  displayName: Style checks
  dependsOn: []
  jobs:
  - job: "Committed"
    displayName: Linting commit history
    pool:
      vmImage: ${{ variables.linux_vm }}
    steps:
    - checkout: self
    - template: v1/azdo-step.yml@gh-install
      parameters:
        git: crate-ci/committed
        target: 'x86_64-unknown-linux-gnu'
        to: $(Build.StagingDirectory)/tools
    - script: |
        echo "Linting commits:"
        git log --graph --oneline HEAD~..HEAD^2
        echo "Against 'committed.toml':"
        $(Build.StagingDirectory)/tools/committed --dump-config -
        echo ""
        echo "If this fails, don't sweat it. We're trying to encourage clear communication and not hinder contributions."
        echo "If it is a reasonable issue and you lack time or feel uncomfortable fixing it yourself,"
        echo "let us know and we can mentor or fix it."
        $(Build.StagingDirectory)/tools/committed HEAD~..HEAD^2 --no-merge-commit -vv
      displayName: Lint commit history
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
    - repository: gh-install
      type: github
      name: crate-ci/gh-install
      endpoint: crate-ci
