[workspace]
members = ["typos", "dict/typos", "dict/typos/codegen"]

[package]
name = "typos-cli"
version = "0.1.1"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT"
edition = "2018"

[[bin]]
name = "typos"
path = "src/main.rs"
doc = false

[badges]
azure-devops = { project = "crate-ci", pipeline = "typos" }
codecov = { repository = "crate-ci/typos" }

[dependencies]
typos = { version = "0.1", path = "typos" }
typos-dict = { version = "0.1", path = "dict/typos" }
failure = "0.1"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
assert_fs = "0.11"
bstr = "0.2"
