[workspace]
members = ["codegen", "typos", "typos-dict"]

[package]
name = "typos-cli"
version = "0.1.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/epage/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT"
edition = "2018"

[[bin]]
name = "typos"
path = "src/main.rs"
doc = false

[badges]
azure-devops = { project = "crate-ci", pipeline = "typos" }
codecov = { repository = "crate-ci/typos" }

[features]
# Support quickly iterating
iterate_unstable = []

[dependencies]
typos = { version = "0.1", path = "typos" }
typos-dict = { version = "0.1", path = "typos-dict" }
failure = "0.1"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
assert_fs = "0.10"
