[workspace]
members = [
    "crates/typos",
    "crates/typos-dict", "crates/typos-dict/codegen", "crates/typos-dict/verify",
    "crates/typos-vars", "crates/typos-vars/codegen",
    "crates/codespell-dict", "crates/codespell-dict/codegen",
    "crates/misspell-dict", "crates/misspell-dict/codegen",
    "crates/wikipedia-dict", "crates/wikipedia-dict/codegen",
    "crates/varcon", "crates/varcon/codegen", "crates/varcon-core",
]

[package]
name = "typos-cli"
version = "0.1.4"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT"
edition = "2018"

[[bin]]
name = "typos"
path = "src/main.rs"
doc = false

[badges]
azure-devops = { project = "crate-ci", pipeline = "typos" }
codecov = { repository = "crate-ci/typos" }

[dependencies]
typos = { version = "^0.3", path = "crates/typos" }
typos-dict = { version = "^0.2", path = "crates/typos-dict" }
typos-vars = { version = "^0.2", path = "crates/typos-vars" }
phf = { version = "0.8", features = ["unicase"] }
unicase = "2.5"
anyhow = "1.0"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4"
env_logger = "0.8"
bstr = "0.2"
ahash = "0.6.1"
difflib = "0.4"
proc-exit = "0.3"
human-panic = "1.0.3"

[dev-dependencies]
assert_fs = "1.0"
predicates = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
