[workspace]
members = [
    "crates/typos",
    "crates/typos-dict", "crates/typos-dict/codegen", "crates/typos-dict/verify",
    "crates/typos-vars", "crates/typos-vars/codegen",
    "crates/codespell-dict", "crates/codespell-dict/codegen",
    "crates/misspell-dict", "crates/misspell-dict/codegen",
    "crates/wikipedia-dict", "crates/wikipedia-dict/codegen",
    "crates/varcon", "crates/varcon/codegen", "crates/varcon-core",
]

[package]
name = "typos-cli"
version = "0.2.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Source Code Spelling Correction"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license = "MIT"
edition = "2018"

[features]
default = ["dict", "vars"]
dict = ["typos-dict"]
vars = ["typos-vars"]

[package.metadata.docs.rs]
no-default-features = true

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/assert-rs/predicates-rs/compare/{{tag_name}}...HEAD", exactly=1},
]

[[bin]]
name = "typos"
path = "src/main.rs"
doc = false

[badges]
azure-devops = { project = "crate-ci", pipeline = "typos" }
codecov = { repository = "crate-ci/typos" }

[dependencies]
typos = { version = "^0.4", path = "crates/typos" }
varcon-core = { version = "1.1.0", path = "crates/varcon-core" }
typos-dict = { version = "^0.3", path = "crates/typos-dict", optional = true }
typos-vars = { version = "^0.3", path = "crates/typos-vars", optional = true }
phf = { version = "0.8", features = ["unicase"] }
unicase = "2.5"
anyhow = "1.0"
structopt = "0.3"
clap = "2"
clap-verbosity-flag = "0.3"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4"
env_logger = "0.8"
bstr = "0.2"
once_cell = "1.2.0"
ahash = "0.7"
difflib = "0.4"
proc-exit = "1.0"
human-panic = "1.0.3"
content_inspector = "0.2.4"
unicode-segmentation = "1.6.0"
derive_more = "0.99.11"
derive_setters = "0.1"
itertools = "0.10"
serde_json = "1.0"
encoding = "0.2"
kstring = "1.0"
typed-arena = "2.0.1"

[dev-dependencies]
assert_fs = "1.0"
predicates = "1.0"
criterion = "0.3"
maplit = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bench]]
name = "checks"
harness = false

[[bench]]
name = "corrections"
harness = false

[[bench]]
name = "tokenize"
harness = false
