[workspace]
members = [
    "crates/typos",
    "crates/typos-dict", "crates/typos-dict/codegen", "crates/typos-dict/verify",
    "crates/typos-vars", "crates/typos-vars/codegen",
    "crates/dictgen",
    "crates/codespell-dict", "crates/codespell-dict/codegen",
    "crates/misspell-dict", "crates/misspell-dict/codegen",
    "crates/wikipedia-dict", "crates/wikipedia-dict/codegen",
    "crates/varcon", "crates/varcon/codegen", "crates/varcon-core",
]

[package]
name = "typos-cli"
version = "1.5.0"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "benches/**/*",
  "examples/**/*"
]

[package.metadata.docs.rs]
no-default-features = true

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/crate-ci/typos/compare/{{tag_name}}...HEAD", exactly=1},
  {file="docker/Dockerfile", search="ARG VERSION=.*", replace="ARG VERSION={{version}}", min=1},
  {file="docs/pre-commit.md", search="rev: .*", replace="rev: {{tag_name}}", exactly=1},
  {file="setup.py", search="TYPOS_VERSION = .*", replace="TYPOS_VERSION = '{{version}}'", exactly=1},
]

[features]
default = ["dict", "vars"]
dict = ["typos-dict"]
vars = ["typos-vars"]


[[bin]]
name = "typos"
path = "src/bin/typos-cli/main.rs"
doc = false

[dependencies]
typos = { version = "^0.8", path = "crates/typos" }
varcon-core = { version = "^2.0.0", path = "crates/varcon-core" }
typos-dict = { version = "^0.8", path = "crates/typos-dict", optional = true }
typos-vars = { version = "^0.8", path = "crates/typos-vars", optional = true }
unicase = "2.5"
anyhow = "1.0"
clap = "3.1"
clap-verbosity-flag = "1.0"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml_edit = { version = "0.13.4", features = ["easy"] }
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["termcolor"] }
atty = "0.2.14"
yansi = "0.5.0"
concolor = { version = "0.0.8" }
concolor-clap = { version = "0.0.9", features = ["api_unstable"] }
bstr = "0.2"
once_cell = "1.2.0"
ahash = "0.7"
difflib = "0.4"
proc-exit = "1.0"
human-panic = "1.0.3"
content_inspector = "0.2.4"
unicode-segmentation = "1.9.0"
derive_more = "0.99.17"
derive_setters = "0.1"
itertools = "0.10"
serde_json = "1.0"
encoding = "0.2"
kstring = "1.0"
typed-arena = "2.0.1"
maplit = "1.0"

[dev-dependencies]
assert_fs = "1.0"
trycmd = "0.12.2"
criterion = "0.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bench]]
name = "checks"
harness = false

[[bench]]
name = "corrections"
harness = false

[[bench]]
name = "tokenize"
harness = false
