[package]
name = "typos-dict"
version = "0.11.7"
description = "Source Code Spelling Correction"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[dependencies]
unicase = "2.7"
dictgen = { version = "^0.2", path = "../dictgen" }

[dev-dependencies]
csv = "1.3"
itertools = "0.12"
edit-distance = "2.1"
unicase = "2.7"
codegenrs = "3.0"
dictgen = { version = "^0.2", path = "../dictgen", features = ["codegen"] }
varcon = { version = "^0.7", path = "../varcon" }
snapbox = { version = "0.4.16", features = ["path"] }
indexmap = "2.2.2"
