[package]
name = "typos-vars"
version = "0.8.4"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2021"
rust-version = "1.60.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
unicase = "2.6"
dictgen = { version = "^0.2", path = "../dictgen" }
varcon-core = { version = "^2.2", path = "../varcon-core", features = ["flags"] }

[dev-dependencies]
varcon = { version = "^0.6", path = "../varcon", features = ["flags"] }
varcon-core = { version = "^2.2", path = "../varcon-core", features = ["flags"] }
typos = { version = "^0.10", path = "../typos" }
unicase = "2.6"
codegenrs = "2.0"
itertools = "0.10"
dictgen = { version = "^0.2", path = "../dictgen", features = ["codegen"] }
snapbox = { version = "0.3.1", features = ["path"] }
