[package]
name = "typos"
version = "0.8.7"
description = "Source Code Spelling Correction"
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/typos"
readme = "../../README.md"
categories = ["development-tools", "text-processing"]
keywords = ["development", "spelling"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
nom = "7.0"
unicode-xid = "0.2.2"
once_cell = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
simdutf8 = "0.1.1"
itertools = "0.10"
log = "0.4"
unicode-segmentation = "1.9.0"
bstr = "0.2"
